# remote_theme: pages-themes/modernist@v0.2.0
remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
title: Pablo's Portfolio
description: Merging Data with Intuition ğŸ“Š ğŸ¯ | ML & DL Assistant Professor @ Colegio de MatemÃ¡ticas Bourbaki | Quantum Engineer | Data Scientist
